name: Working dirs & shells
on: [push]
jobs:
    display-wp-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory & list files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-wp-info-windows:
        runs-on: windows-latest
        steps:
            - name: Display working directory & list files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
